services:
  postgres:
    image: postgres:16
    container_name: moonDB
    environment:
      POSTGRES_DB: moondb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/init_postgres.sql:/docker-entrypoint-initdb.d/init_postgres.sql:ro
